// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDN2oS6hMAGJ0qe0m-h8aov8Zj5WUUDc',
    appId: '1:879139655454:web:0a048e3ed303776011030f',
    messagingSenderId: '879139655454',
    projectId: 'flutter-app-ff3c8',
    authDomain: 'flutter-app-ff3c8.firebaseapp.com',
    storageBucket: 'flutter-app-ff3c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd11v_yMMqtMUgViDwwHZD7lMfimlnWW4',
    appId: '1:879139655454:android:6d9a84d9d48ec49411030f',
    messagingSenderId: '879139655454',
    projectId: 'flutter-app-ff3c8',
    storageBucket: 'flutter-app-ff3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtrsiBRaXyKELffebtCiNve0EhSWuQAc',
    appId: '1:879139655454:ios:a0b96f3a4892fd7511030f',
    messagingSenderId: '879139655454',
    projectId: 'flutter-app-ff3c8',
    storageBucket: 'flutter-app-ff3c8.appspot.com',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtrsiBRaXyKELffebtCiNve0EhSWuQAc',
    appId: '1:879139655454:ios:e311c92c1dc08be711030f',
    messagingSenderId: '879139655454',
    projectId: 'flutter-app-ff3c8',
    storageBucket: 'flutter-app-ff3c8.appspot.com',
    iosBundleId: 'com.example.aplicacion.RunnerTests',
  );
}
